-- Additive deployment only. Run with application writers stopped, before deploying sync writers.
CREATE TABLE "sync_changes" (
  "id" UUID NOT NULL,
  "user_id" UUID NOT NULL,
  "device_id" UUID,
  "entity_type" VARCHAR(32) NOT NULL,
  "entity_id" UUID NOT NULL,
  "operation" VARCHAR(8) NOT NULL,
  "version" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "sync_changes_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "sync_changes_entity_check" CHECK (entity_type IN ('account_types','accounts','categories','transactions','user_profiles')),
  CONSTRAINT "sync_changes_operation_check" CHECK (operation IN ('CREATE','UPDATE','DELETE')),
  CONSTRAINT "sync_changes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "sync_changes_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "sync_changes_version_key" ON "sync_changes"("version");
CREATE INDEX "sync_changes_user_id_version_idx" ON "sync_changes"("user_id","version");
CREATE INDEX "sync_changes_entity_type_entity_id_device_id_idx" ON "sync_changes"("entity_type","entity_id","device_id");

-- Historical bootstrap: bounded pull pages read these events, not an unbounded snapshot.
-- UUIDv7 event IDs use migration time with cryptographically random remaining bits.
CREATE FUNCTION pg_temp.sync_event_id() RETURNS uuid LANGUAGE SQL VOLATILE AS $$
  SELECT (lpad(to_hex(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint),12,'0') || '7' || substr(replace(gen_random_uuid()::text,'-',''),14,3) || '8' || substr(replace(gen_random_uuid()::text,'-',''),18,15))::uuid
$$;
WITH audience AS (
  SELECT a.id AS account_id, a.user_id FROM accounts a
  UNION
  SELECT ga.account_id, ug.user_id FROM group_accounts ga
  JOIN groups g ON g.id = ga.group_id AND g.is_active AND g.deleted_at IS NULL
  JOIN user_groups ug ON ug.group_id = g.id
  JOIN users u ON u.id = ug.user_id AND u.status = 'ACTIVE' AND u.deleted_at IS NULL
  JOIN accounts a ON a.id = ga.account_id AND a.deleted_at IS NULL
  JOIN account_types at ON at.id = a.account_type_id AND at.deleted_at IS NULL
), initial AS (
  SELECT r.user_id, 'accounts'::text AS entity_type, a.id AS entity_id, a.deleted_at FROM accounts a JOIN audience r ON r.account_id = a.id
  UNION
  SELECT at.user_id, 'account_types', at.id, at.deleted_at FROM account_types at
  UNION
  SELECT r.user_id, 'account_types', at.id, at.deleted_at FROM audience r JOIN accounts a ON a.id = r.account_id JOIN account_types at ON at.id = a.account_type_id
  UNION
  SELECT c.user_id, 'categories', c.id, c.deleted_at FROM categories c
  UNION
  SELECT r.user_id, 'categories', c.id, c.deleted_at FROM audience r JOIN accounts a ON a.id = r.account_id JOIN categories c ON c.user_id = a.user_id
  UNION
  SELECT r.user_id, 'transactions', t.id, t.deleted_at FROM transactions t JOIN audience r ON r.account_id = t.account_id
  WHERE NOT EXISTS (SELECT 1 FROM investment_transactions it WHERE it.linked_transaction_id = t.id)
  UNION
  SELECT p.user_id, 'user_profiles', p.user_id, p.deleted_at FROM user_profiles p
)
INSERT INTO sync_changes (id,user_id,entity_type,entity_id,operation)
SELECT pg_temp.sync_event_id(),user_id,entity_type,entity_id,CASE WHEN deleted_at IS NULL THEN 'CREATE' ELSE 'DELETE' END
FROM initial ORDER BY entity_type,entity_id,user_id;
